server:
  port: 8005
spring:
  application:
    name: deptProvider8005
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicecloud_db_01
    username: root
    password: 123456
eureka:
  instance:
    instance-id: deptprovider8005
  client:
    service-url:
      defaultZone: http://eurekaserver7004.com:7004/eureka/
mybatis:
  mapper-locations: classpath:/mybatis/**/mapper/*.xml
  type-aliases-package: com.ultrapower.entity
