server:
  port: 7004
eureka:
  instance:
    hostname: eurekaserver7004.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/